import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const base = process.env.APP_URL || 'http://127.0.0.1:3001';
await mkdir(new URL('../artifacts/', import.meta.url), { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.route('**/api/casting/guess-genders', route => route.fulfill({ json: { guesses: route.request().postDataJSON().names.map(name => ({ name, gender: 'unknown' })) } }));
const errors = [];
const externalRequests = [];
let renderRequests = 0;
page.on('pageerror', (error) => errors.push(error.message));
page.on('request', request => { const url = new URL(request.url()); if (request.method() === 'POST' && url.pathname === '/api/render') renderRequests++; if (!['127.0.0.1', 'localhost'].includes(url.hostname)) externalRequests.push(url.href); });
try {
  await page.goto(base);
  await page.waitForSelector('main');
  await page.waitForFunction(() => !document.querySelector('[data-action="render"]')?.disabled);
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true });
  const controls = await page.locator('button,input,select,textarea,a').evaluateAll((elements) => elements.map((element) => ({
    tag: element.tagName, id: element.id, label: element.getAttribute('aria-label'), text: element.textContent?.trim().slice(0, 150),
  })));
  await writeFile('artifacts/browser-controls.json', JSON.stringify(controls, null, 2));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile must fit viewport without horizontal overflow');

  // Import/edit/restore through the real UI; tiny original dialogue reuses live-check cache.
  await page.setViewportSize({ width: 1440, height: 1000 });
  const source = 'INT. REHEARSAL ROOM - DAY\n\nPARTNER: Are you ready to begin?\nJORDAN: Yes. Let us take it from the top.\nPARTNER: Good. The stage is yours.\n\nEXT. STAGE - NIGHT\n\nJORDAN: Yes. Let us take it from the top.';
  await page.locator('#file-input').setInputFiles({ name: 'Rehearsal.fountain', mimeType: 'text/plain', buffer: Buffer.from(source) });
  await page.waitForFunction(() => document.querySelectorAll('[data-action="scene"]').length === 2 && document.querySelector('#my-role')?.textContent.includes('actor'));
  await page.locator('[data-action="edit"]').click();
  await page.locator('#script-name').fill('The rehearsal room');
  assert.equal(await page.locator('#script-source').inputValue(), source);
  await page.locator('#save-script').click();
  await page.locator('#my-role').selectOption('JORDAN');
  assert.equal(await page.locator('[data-cast="JORDAN"]').inputValue(), 'MyVoice');
  await page.locator('[data-cast="PARTNER"]').selectOption('Stock-Mica');
  await page.locator('#line-gap').fill('0.5');
  await page.locator('#line-gap').dispatchEvent('change');
  await page.reload();
  await page.waitForFunction(() => !document.querySelector('[data-action="render"]')?.disabled);
  assert.equal(await page.locator('#my-role').inputValue(), 'JORDAN');
  assert.equal(await page.locator('[data-cast="PARTNER"]').inputValue(), 'Stock-Mica');
  await page.locator('[data-action="render"]').click();
  await page.locator('a[download]').first().waitFor({ timeout: 180000 });
  assert.equal(await page.locator('a[download]').count(), 2);
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => document.querySelector('audio').currentTime > 0.2);
  await page.locator('[data-action="play"]').click();
  assert.ok(await page.locator('audio').evaluate((audio) => audio.paused));
  assert.equal(await page.locator('#player-status').innerText(), 'Ready to rehearse');
  await page.locator('#seek').fill('2.3');
  await page.locator('[data-action="mode-practice"]').click();
  await page.waitForFunction(() => { const a = document.querySelector('audio'); return a.src.endsWith('-practice.wav') && a.readyState >= 1 && a.currentTime >= 2.29; });
  assert.ok(await page.locator('audio').evaluate((audio) => audio.currentTime < 2.4 && audio.paused));
  await page.locator('#playback-rate').selectOption('0.75');
  assert.equal(await page.locator('audio').evaluate((audio) => audio.playbackRate), 0.75);
  await page.locator('[data-action="loop"]').click();
  assert.ok(await page.locator('audio').evaluate((audio) => audio.loop));
  await page.locator('#hide-lines').check({ force: true });
  assert.equal(await page.locator('.my-line [data-action="reveal"]').count(), 1);
  assert.equal(await page.locator('.my-line p').count(), 0);
  await page.locator('[data-action="reveal"]').click();
  assert.ok((await page.locator('.my-line p').innerText()).includes('take it from the top'));
  const downloadWait = page.waitForEvent('download');
  await page.locator('a[download]').nth(1).click();
  const download = await downloadWait;
  await download.saveAs('artifacts/browser-practice.wav');
  assert.equal(await download.failure(), null);
  await page.screenshot({ path: 'artifacts/rehearsal-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/rehearsal-mobile.png', fullPage: true });
  await page.locator('[data-action="scene"]').nth(1).click();
  assert.equal(await page.locator('a[download]').count(), 0, 'Scene change invalidates previous export');
  assert.match(await page.locator('[data-action="play"]').getAttribute('aria-label'), /Make audio and play scene/);
  await page.locator('[data-action="scene"]').first().click();
  assert.equal(await page.locator('a[download]').count(), 2, 'Returning to a rendered scene restores downloads');
  assert.ok(await page.locator('[data-action="play"]').isEnabled());
  assert.equal(renderRequests, 1, 'Scene revisit uses existing result without rerendering');
  const savedPracticeUrl = await page.locator('a[download]').nth(1).getAttribute('href');
  await page.reload();
  await page.locator('a[download]').first().waitFor();
  assert.equal(await page.locator('a[download]').nth(1).getAttribute('href'), savedPracticeUrl, 'Refresh restores the same rendered tracks');
  assert.ok(await page.locator('[data-action="play"]').isEnabled());
  assert.equal(await page.locator('#player-status').innerText(), 'Ready to rehearse');
  assert.equal(renderRequests, 1, 'Refresh must not request a new render');
  await page.locator('[data-cast="PARTNER"]').selectOption('Stock-Amber');
  assert.equal(await page.locator('a[download]').count(), 0, 'Changed cast cannot use stale audio');
  await page.route('**/api/health', route => route.fulfill({ json: { tts: { ok: false }, stt: { ok: false } } }));
  await page.route('**/api/voices', route => route.fulfill({ status: 503, json: { error: 'Voice engine unavailable' } }));
  await page.reload();
  await page.waitForFunction(() => document.querySelector('.local-badge')?.textContent.includes('unavailable'));
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('script-glow:v1')).cast.PARTNER), 'Stock-Amber', 'Offline engine must preserve voice choices');
  await page.unroute('**/api/health');
  await page.unroute('**/api/voices');
  await page.locator('[data-action="reconnect"]').evaluate((element) => element.click());
  await page.waitForFunction(() => !document.querySelector('[data-action="render"]')?.disabled);
  assert.equal(await page.locator('[data-cast="PARTNER"]').inputValue(), 'Stock-Amber');
  assert.deepEqual(errors, [], 'No uncaught browser errors');
  assert.deepEqual(externalRequests, [], 'App and fonts must not require external browser requests');
  console.log('PASS: responsive UI; import/edit/restore; actor cast; live render; play/pause/seek; practice switch preserves time; speed/loop; hide/reveal; WAV download; scene/refresh restore without rerender; cast invalidation; offline cast retention; local fonts.');
} finally {
  await browser.close();
}
