import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { voiceCatalog } from '../src/voice-catalog.ts';
import { encodeWav } from '../server/audio.js';

await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.route('**/api/casting/guess-genders', route => route.fulfill({ json: { guesses: route.request().postDataJSON().names.map(name => ({ name, gender: 'unknown' })) } }));
const errors = []; page.on('pageerror', error => errors.push(error.message));
let renders = 0, input;
const sample = encodeWav(Buffer.alloc(48000 * 10));
const fulfillAudio = route => {
  const range = route.request().headers().range?.match(/^bytes=(\d+)-(\d*)$/);
  if (!range) return route.fulfill({ contentType: 'audio/wav', body: sample });
  const start = Number(range[1]), end = range[2] ? Math.min(Number(range[2]), sample.length - 1) : sample.length - 1;
  return route.fulfill({ status: 206, contentType: 'audio/wav', headers: { 'Accept-Ranges': 'bytes', 'Content-Range': `bytes ${start}-${end}/${sample.length}` }, body: sample.subarray(start, end + 1) });
};
await page.route('**/api/health', route => route.fulfill({ json: { tts: { ok: true } } }));
await page.route('**/api/voices', route => route.fulfill({ json: { voices: [...Object.keys(voiceCatalog), 'Unknown-Voice'] } }));
await page.route('**/api/render', route => { renders++; input = route.request().postDataJSON(); return route.fulfill({ status: 202, json: { jobId: 'preview-fixture' } }); });
await page.route('**/api/jobs/preview-fixture', route => route.fulfill({ json: { id: 'preview-fixture', status: 'complete', completed: 2, total: 2, result: { fullUrl: '/audio/preview-fixture-full.wav', practiceUrl: '/audio/preview-fixture-practice.wav', duration: 10, cues: input.scene.lines.filter(line => line.kind === 'dialogue').map((line, i) => ({ lineId: line.id, character: line.character, start: i * 3, end: i * 3 + 2 })) } } }));
await page.route('**/audio/preview-fixture-*.wav', fulfillAudio);
try {
  await page.goto('http://127.0.0.1:3001');
  const source = 'SCENE 1\nJORDAN: Hello.\nPARTNER: Welcome.\n\nSCENE 2\nJORDAN: Ready.';
  await page.locator('#file-input').setInputFiles({ name: 'Voices.txt', mimeType: 'text/plain', buffer: Buffer.from(source) });
  await page.waitForFunction(() => document.querySelector('[data-cast="PARTNER"]')?.value);
  await page.locator('#my-role').selectOption('JORDAN');
  assert.equal(await page.locator('[data-cast="JORDAN"]').inputValue(), 'MyVoice');
  for (const id of Object.keys(voiceCatalog).filter(id => id.startsWith('VoiceZero-') || /Stock-(Slate|Quartz)/.test(id))) {
    assert.equal(await page.locator(`[data-cast="PARTNER"] option[value="${id}"]`).count(), 1);
    assert.ok(voiceCatalog[id].previewUrl, `${id}: preview published`);
    const response = await page.request.get(`http://127.0.0.1:3001${voiceCatalog[id].previewUrl}`);
    assert.equal(response.status(), 200, `${id}: served preview`);
    assert.match(response.headers()['content-type'], /audio/);
    assert.equal((await response.body()).toString('ascii', 0, 4), 'RIFF');
  }
  await page.locator('[data-cast="PARTNER"]').selectOption('Stock-Slate');
  assert.match(await page.locator('[data-cast="PARTNER"]').locator('..').locator('.voice-description').innerText(), /American|US/i);
  await page.locator('[data-action="render"]').click();
  await page.locator('a[download]').first().waitFor();
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => document.querySelector('#scene-audio').currentTime > 0.1);
  const saved = await page.locator('a[download]').first().getAttribute('href');
  const cast = await page.locator('[data-cast="PARTNER"]').inputValue();
  await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#voice-preview-audio')?.currentTime > 0.1);
  assert.ok(await page.locator('#scene-audio').evaluate(audio => audio.paused));
  assert.equal(await page.locator('a[download]').first().getAttribute('href'), saved);
  assert.equal(await page.locator('[data-cast="PARTNER"]').inputValue(), cast);
  assert.equal(renders, 1, 'Preview must not render script');
  await page.getByRole('button', { name: 'Stop voice for PARTNER', exact: true }).click();
  assert.equal(await page.locator('#voice-preview-audio').count(), 0);
  await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).click();
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => !document.querySelector('#scene-audio').paused);
  assert.equal(await page.locator('#voice-preview-audio').count(), 0, 'Rehearsal stops preview');
  await page.locator('[data-action="play"]').click();
  await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).click();
  await page.locator('#scene-select').selectOption('scene-2');
  assert.equal(await page.locator('#voice-preview-audio').count(), 0, 'Scene change stops preview');
  await page.locator('#scene-select').selectOption('scene-1');
  assert.equal(await page.locator('a[download]').first().getAttribute('href'), saved);
  await page.locator('[data-cast="PARTNER"]').selectOption('VoiceZero-Alana');
  assert.match(await page.locator('[data-cast="PARTNER"]').locator('..').locator('.voice-description').innerText(), /Midwest/i);
  await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#voice-preview-audio')?.currentTime > 0.1);
  await page.locator('#voice-preview-audio').evaluate(audio => { audio.currentTime = audio.duration - 0.05; });
  await page.waitForFunction(() => !document.querySelector('#voice-preview-audio'));
  assert.match(await page.locator('#voice-preview-status').innerText(), /finished/);
  await page.route('**/voice-previews/VoiceZero-Alana.wav', route => route.fulfill({ status: 404 }));
  await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#voice-preview-status')?.textContent.includes('unavailable'));
  await page.unroute('**/voice-previews/VoiceZero-Alana.wav');
  await page.locator('[data-cast="PARTNER"]').selectOption('Unknown-Voice');
  assert.ok(await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).isDisabled());
  assert.equal(await page.locator('[data-cast="PARTNER"]').locator('..').locator('.voice-description').count(), 0);
  await page.locator('[data-cast="PARTNER"]').selectOption('Stock-Quartz');
  await page.reload();
  await page.waitForFunction(() => document.querySelector('[data-cast="PARTNER"]')?.value === 'Stock-Quartz');
  assert.equal(await page.locator('[data-cast="JORDAN"]').inputValue(), 'MyVoice');
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: 'artifacts/voice-library-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.equal(await page.locator('.settings-panel > :first-child h2').innerText(), 'Set the pace');
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: 'artifacts/voice-library-mobile.png', fullPage: true });
  await page.route('**/api/voices', route => route.fulfill({ status: 503, json: { error: 'Offline' } }));
  await page.reload();
  await page.getByRole('button', { name: 'Preview voice for PARTNER', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#voice-preview-audio')?.currentTime > 0.1);
  assert.equal(renders, 1, 'Local preview works even when voice service is offline');
  assert.deepEqual(errors, []);
  console.log('PASS: 12 new catalog voices and served previews; preview/play mutual exclusion; stop/end/error handling; cast/render preservation; source labels; unknown fallback; mobile; actor retained. Render audio is mocked; preview WAVs are real assets.');
} finally { await browser.close(); }
